name: Creative Hipster Blog Title
description: I'm not lazy - my code's just compiling.
url: http://tnbeatty.github.com/blog.html
author: Nate Beatty

email: nate@strabogis.com

# Pygments for syntax highlighting
pygments: true

# Server will automatically regenerate modified files
auto: true

# Do not publish posts with future date
future: false

# Late Symantic Indexing
lsi: true